export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADING_COMPLETED_SUCCESS = 'PAGE_LOADING_COMPLETED_SUCCESS';
// 404 page
export const PAGE_LOADING_COMPLETED_FAILED = 'PAGE_LOADING_COMPLETED_FAILED';
// Do a retry
export const PAGE_LOADING_FAILED = 'PAGE_LOADING_FAILED';