export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADING_COMPLETED_SUCCESS = 'PAGE_LOADING_COMPLETED_SUCCESS';
// 404 page
export const PAGE_LOADING_COMPLETED_FAILED = 'PAGE_LOADING_COMPLETED_FAILED';
// Do a retry
export const PAGE_LOADING_FAILED = 'PAGE_LOADING_FAILED';


export const OPERATION_LOADING = 'OPERATION_LOADING';
export const OPERATION_LOADING_COMPLETED = 'OPERATION_LOADING_COMPLETED';
export const OPERATION_LOADING_ERROR = 'OPERATION_LOADING_ERROR';