export const PAGE_LOADING = 'PAGE_LOADING';
export const PAGE_LOADING_COMPLETED_SUCCESS = 'PAGE_LOADING_COMPLETED_SUCCESS';
export const PAGE_LOADING_COMPLETED_FAILED = 'PAGE_LOADING_COMPLETED_FAILED';
export const PAGE_LOADING_FAILED = 'PAGE_LOADING_FAILED';
export const OPERATION_LOADING = 'OPERATION_LOADING';
export const OPERATION_LOADING_COMPLETED = 'OPERATION_LOADING_COMPLETED';
export const OPERATION_LOADING_ERROR = 'OPERATION_LOADING_ERROR';
export const DEFAULT_CATEGORY_CODE = 'OTHERS';
export const COMPONENT_STATUS_INVALID = 'COMPONENT_STATUS_INVALID';
export const COMPONENT_STATUS_VALID = 'COMPONENT_STATUS_VALID';
export const COMPONENT_LOADER = 'COMPONENT_LOADER';
export const COMPONENT_PRODUCT_FACTORY = 'COMPONENT_PRODUCT_FACTORY';
export const COMPONENT_PRODUCT_FACTORY_INVALID = 'COMPONENT_PRODUCT_FACTORY_INVALID';
export const COMPONENT_BASIC_DETAILS = 'COMPONENT_BASIC_DETAILS';
export const COMPONENT_ATTRIBUTES = 'COMPONENT_ATTRIBUTES';
export const COMPONENT_ADVANCED_DETAILS = 'COMPONENT_ADVANCED_DETAILS';
export const COMPONENT_PREFERENCES = 'COMPONENT_PREFERENCES';
export const COMPONENT_COST_DETAILS = 'COMPONENT_COST_DETAILS';
export const COMPONENT_MAPPER = {
    'basic_details': COMPONENT_BASIC_DETAILS,
    'advanced_details': COMPONENT_ADVANCED_DETAILS,
    'cost_details': COMPONENT_COST_DETAILS,
    'preferences': COMPONENT_PREFERENCES,
    'attributes': COMPONENT_ATTRIBUTES
}
export const NO_DISCOUNT = 'NO_DISCOUNT';
export const INSTANT_AMOUNT = 'INSTANT_AMOUNT';
export const INSTANT_PERCENTAGE = 'INSTANT_PERCENTAGE';




