module.exports = {
    apiAuthenticator: require('./api-authenticator'),
    createSessionWithFacebook: require('./create-session-with-facebook'),
    logoutSession: require('./logout-session'),
    addProduct: require('./add-product'),
    editProductById: require('./edit-product-by-id'),
    removeProductById: require('./remove-product-id'),
    getProductById: require('./get-product-by-id'),
    getFeaturedProducts: require('./get-featured-products'),
    getProducts: require('./get-products'),
    getFilteredProducts: require('./get-filtered-products'),
    getProductsByCategory: require('./get-products-by-category'),
    addProductToCart: require('./cart/add-product-to-cart'),
    removeProductFromCart: require('./cart/remove-product-from-cart'),
    editProductInCart: require('./cart/edit-product-in-cart'),
    getCart: require('./cart/get-cart'),
    validateUserSession: require('./validate-user-session'),
    createInstantOrder: require('./create-instant-order'),
    getOrderById: require('./get-order-by-id'),
    patchOrderById: require('./patch-order-by-id'),
    getPaymentPlan: require('./get-payment-plan'),
    razorpayPaymentComplete: require('./razorpay-payment-complete'),
    updateDeliveryPincode: require('./update-delivery-pincode.js')
}