module.exports = {
    X_TINNAT_SECURITY_CONTEXT: 'x-tinnat-security-context',
    X_TINNAT_DEBUG_ID: 'x-tinnat-debug-id',
    ADMIN_USER: 'admin',
    ADMIN_USER_KEY: 'tinnat',
    TINNAT_WEB: 'tinnat_web',
    TINNAT_WEB_GUEST: 'tinnat_guest',
    TINNAT_WEB_GUEST_KEY: 'tinnat_guest_secret',
    TINNAT_FACEBOOK_OAUTH: 'tinnat_facebook_oauth',
    ORDER_LIFE_TIME: 14400000,
    ENVIRONMENT_PRODUCTION: 'ENVIRONMENT_PRODUCTION',
    ENVIRONMENT_DEVELOPMENT: 'ENVIRONMENT_DEVELOPMENT',
    status: {
        COMPLETED: 'COMPLETED',
        SUCCESS: 'SUCCESS',
        FAILURE: 'FAILURE'
    },
    CURRENCY: {
        INR: 'INR'
    },
    INTENT: {
        CAPTURE: 'CAPTURE',
    },
    COUNTRY_CODE: {
        IN: 'IN'
    },
    API_NAME: {
        GET_PRODUCTS: 'get_products',
        GET_FEATURED_PRODUCTS: 'get_featured_products',
        GET_FILTERED_PRODUCTS: 'get_filtered_products',
        GET_PRODUCTS_BY_CATEGORY: 'get_products_by_category',
        ADD_PRODUCT: 'add_product',
        GET_PRODUCT_BY_ID: 'get_product_by_id',
        EDIT_PRODUCT_BY_ID: 'edit_product_by_id',
        REMOVE_PRODUCT_BY_ID: 'remove_product_by_id',
        CREATE_INSTANT_ORDER: 'create_instant_order',
        GET_ORDER_BY_ID: 'get_order_by_id',
        PATCH_ORDER_BY_ID: 'patch_order_by_id',
        GET_PAYMENT_PLAN: 'get_payment_plan',
        RAZORPAY_PAYMENT_COMPLETE: 'razorpay_payment_complete',
        UPDATE_DELIVERY_PINCODE: 'update_delivery_pincode',
        GET_PAYMENT_ACTIVITY: 'get_payment_activity',
        GET_PAYMENT_ACTIVITY_INTERNAL: 'get_payment_activity_internal',
        SEARCH_TRANSACTIONS: 'search_transactions',
        GET_KPIS: 'get_kpis',
        GET_LOGS: 'get_logs',
        BUSINESS_PRODUCT_FILTER: 'business_filter_products',
        GET_ALL_PURCHASES: 'get_all_purchases',
        GET_PURCHASE_BY_ID: 'get_purchase_by_id'
    },
    WEB_NAME: {
        GET_PRODUCT: 'get_product',
        GET_ORDERS: 'account_activity_orders',
        GET_ORDER_BY_ID: 'account_activity_order',
        WHOAMI: 'whoami',
        HOME: 'home',
        ABOUT: 'about',
        GET_PRODUCTS: 'get_products',
        HELP: 'help',
        CONTACTUS: 'contact_us',
        INSTANT_PURCHASE_ORDER: 'instant_purchase_order',
        INSTANT_PURCHASE_PAYMENT: 'instant_purchase_payment',
        INSTANT_PURCHASE_CONFIRMATION: 'instant_purchase_confirmation',
        GET_PAYMENT_ACTIVITY: 'get_payment_activity',
        BUSINESS_DASHBOARD: 'business_dashboard',
        IDSEARCH: 'idsearch',
        NOT_FOUND: 'not_found',
        LOGIN: 'login',
        BUSINESS_ACTIVITY: 'business_activity',
        BUSINESS_ADD_PRODUCT: 'business_add_product',
        BUSINESS_UPDATE_PRODUCT: 'business_update_product',
        BUSINESS_VIEW_PRODUCT: 'business_view_product',
        BUSINESS_VIEW_PRODUCTS: 'business_view_products'
    },
    SOFT_DESCRIPTOR: 'Tinnos India',
    ORDER_CREATED: 'ORDER_CREATED',
    ORDER_PAYMENT_PENDING: 'PAYMENT_PENDING',
    ORDER_COMPLETED: 'COMPLETED',
    RECEIPT_PREFIX: 'R-',
    ORDER_PREFIX: 'ORDER-',
    COMPLETED: 'COMPLETED',
    MAILSERVICE: {
        NOREPLY: 'noreply',
        ORDERCONFIRMATION: 'orderconfirmation'
    },
    DELIVERABLE: 'DELIVERABLE',
    NOT_DELIVERABLE: 'NOT_DELIVERABLE',
    DELIVERY_INITIATED: 'INITIATED',
    ORDER_PAYMENT: 'ORDER_PAYMENT',
    PERSONAL_ACCOUNT: 'PERSONAL_ACCOUNT',
    GUEST: 'GUEST',
    PERSONAL: 'PERSONAL',
    BUSINESS: 'BUSINESS',
    ADMIN: 'ADMIN',
    FACEBOOK: 'FACEBOOK',
    RAZORPAY: 'RAZORPAY',
    WEB: 'WEB',
    API: 'API'
};
